#=============================setup:Tkinter==================================
from tkinter import*
import tkinter.ttk as t
from PIL import ImageTk,Image
win=Tk()
w=win.winfo_screenwidth()
h=win.winfo_screenheight()
win.geometry("%dx%d+0+0"%(w,h-100))
win.title("RAJALAKSHMI ENGINEERING COLLEGE VLAB")
nb=t.Notebook(win)
s1=t.Frame(nb)
s2=t.Frame(nb)
win.iconbitmap('recicon.ico')
img=ImageTk.PhotoImage(Image.open("rec.png"))
imglab1=Label(s1,image=img)
imglab2=Label(s2,image=img)
imglab1.pack(side=TOP)
imglab2.pack(side=TOP)
#===============================
#===============================setup:frames===================================


nb.add(s1,text="Experiment")
nb.add(s2,text="about")
nb.pack(fill="both",expand="yes")
tab1_label=Label(s1,text="Hele-Shaw flow:",font=("calibri",20,"underline bold italic"))
tab1_label.pack(side=TOP,anchor="w")
tab1_label=Label(s1,text="Hele-Shaw flow is defined as Stokes flow between two parallel flat plates",font=("calibri",15," bold italic"))
tab1_label.pack()
tab1_label=Label(s1,text=" separated by an infinitesimally small gap, named after Henry Selby Hele-Shaw,",font=("calibri",15," bold italic"))
tab1_label.pack()
tab1_label=Label(s1,text="who studied the problem in 1898",font=("calibri",15," bold italic"))
tab1_label.pack()
tab1_label=Label(s1,text="EXPERIMENT:",font=("calibri",18,"bold italic"))
tab1_label.pack(side=LEFT)

tab2=Label(s2,text="TEAM:",font=("calibri",20,"underline bold italic"))
tab2.pack(side=TOP,anchor="w",pady=50)
tab2=Label(s2,text="SANTHOSH RAAJAA.S\nVIGNESH KUMAR.S\nAKASH.K\n",font=("calibri",15,"bold italic"))
tab2.pack(side=TOP)
tab2=Label(s2,text="Thanks to",font=("calibri",20,"bold italic"))
tab2.pack(side=LEFT,anchor="w",pady=50)
tab2=Label(s2,text="SHEBAZAHAMED JP\nEZHILMARAN G",font=("calibri",15,"bold italic"))
tab2.pack(side=BOTTOM)

#===============================setup:turtle=============================
from turtle import*

#====================================heleshaw:circle==================================
def circle(*args):
    resetscreen()
    t=Turtle();t.hideturtle()
    t1=Turtle();t1.hideturtle()
    t2=Turtle();t2.hideturtle()
    t3=Turtle();t3.hideturtle()    
    setup(800,650)
    title("HELE SHAW")
    t2.speed("normal")
    t2.hideturtle()
    t2.up()
    t2.goto(-176.7,285)
    t2.write("SETTING UP THE APPARATUS",move=True,font=("arial",15))
    t.speed("normal")
    t.pensize(5)
    t1.speed("fastest")
    t.up()
    t1.up()
    t.goto(176.7,275)
    t1.goto(166.7,265)
    t.right(90)
    t1.right(90)
    t.down()
    t1.down()
    t.forward(400)
    t1.forward(380)
    t.right(45)
    t1.right(45)
    t.forward(250)
    t1.forward(235)
    t.right(90)
    t1.right(90)
    t.forward(250)
    t1.forward(235)
    t.right(45)
    t1.right(45)
    t.forward(400)
    t1.forward(380)
    t.right(90)
    t1.right(90)
    t.fd(353.5)
    t1.fd(332.34)
    t1.hideturtle()
    t.hideturtle()


    
    t3.up()             #circle
    t3.pensize(10)
    t3.goto(0,100)
    t3.down()
    t3.color("gray","black")
    t3.circle(-50)
    t3.hideturtle()
    t2.clear()

    
    but=Turtle();but.speed("fastest");but.hideturtle()
    but2=Turtle();but2.speed("fastest");but2.hideturtle()
    but.up()
    but.goto(120,-250)
    but.down()
    for i in range(2):
            
            but.fd(100)
            but.right(90)
            but.fd(30)
            but.right(90)
    but.up()
    but.goto(125,-280)
    but.down()
    but.write("Proceed",font=("calibri",20,"normal"))

    but2.up()
    but2.goto(-120,-250)
    but2.down()
    for i in range(2):
            
            but2.fd(-100)
            but2.right(-90)
            but2.fd(-30)
            but2.right(-90)
    but2.up()
    but2.goto(-200,-280)
    but2.down()
    but2.write("ellipse",font=("calibri",20,"normal"))
    def proceed(x,y):
        print(x,y)
        if x>120 and x<220 and y<-250 and  y>-280:        
                but.reset()
                circ()
        elif x<-120 and x>-220 and y<-250 and  y>-280:
                ellipse()       
            
    onscreenclick(proceed,1)
    listen()


    def circ():
        f1=Turtle();f1.speed("normal");f1.hideturtle()
        f2=Turtle();f2.speed("fastest");f2.hideturtle()
        f3=Turtle();f3.speed("fastest");f3.hideturtle()
        f4=Turtle();f4.speed("fastest");f4.hideturtle()
        f5=Turtle();f5.speed("fastest");f5.hideturtle()
        f6=Turtle();f6.speed("fastest");f6.hideturtle()
        f7=Turtle();f7.speed("fastest");f7.hideturtle()
        f8=Turtle();f8.speed("fastest");f8.hideturtle()
        f9=Turtle();f9.speed("fastest");f9.hideturtle()
        f10=Turtle();f10.speed("fastest");f10.hideturtle()
        f11=Turtle();f11.speed("fastest");f11.hideturtle()
        f12=Turtle();f12.speed("fastest");f12.hideturtle()
        f13=Turtle();f13.speed("fastest");f13.hideturtle()
        pt1=Turtle();pt1,speed("fastest");pt1.hideturtle()
        pt2=Turtle();pt2,speed("fastest");pt2.hideturtle()
        pt3=Turtle();pt3,speed("fastest");pt3.hideturtle()
        pt4=Turtle();pt4,speed("fastest");pt4.hideturtle()

        x=166
        for t in (f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13):
            t.up()
            t.color("pink")
            
        for t in f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13:
            t.goto(x,265)
            t.right(90)
            x-=27.5
        for t in (f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,pt1,pt2,pt3,pt4):
            t.down()
            if t==f1:
                t.fd(380)
                t.right(45)
                t.fd(232)
            elif t==f13:
                t.fd(380)
                t.left(45)
                t.fd(232)
            elif t==f6:
                t.pensize(6)
                t.fd(160)
                t.left(45)
                t.fd(10)
                t.circle(-80,110)
                t.setheading(270)
                t.fd(230)
            elif t==f8:
                t.pensize(6)
                t.fd(160)
                t.right(45)
                t.fd(10)
                t.circle(80,110)
                t.setheading(270)
                t.fd(230)
            elif t==f7:
                t.pensize(6)
                t.fd(155)
                t.setheading(180)
                t.circle(50,30)
                t.up()
                t.goto(0,110)
                t.setheading(0)
                t.down()
                t.circle(-50,30)
            elif t==f9:
                t.pensize(6)
                t.fd(140)
                t.right(45)
                t.circle(100,100)
                t.setheading(270)
                t.fd(180)
                t.left(30)
                t.fd(55)
            elif t==f5:
                t.pensize(6)
                t.fd(140)
                t.left(45)
                t.circle(-100,100)
                t.setheading(270)
                t.fd(180)
                t.right(30)
                t.fd(60)
            elif t==f4:
                t.pensize(6)
                t.fd(130)
                t.left(45)
                t.circle(-125,90)
                t.right(10)
                t.fd(20)
                t.setheading(270)
                t.fd(145)
                t.right(45)
                t.fd(10)
            elif t==f10:
                t.pensize(6)
                t.fd(130)
                t.right(45)
                t.circle(125,90)
                t.right(10)
                t.fd(20)
                t.setheading(270)
                t.fd(140)
                t.left(45)
                t.fd(10)
            elif t==f3:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.left(20)
                t.circle(-400,15)
                t.up()
                t.goto(110,-90)
                t.down()
                t.setheading(90)
                t.right(20)
                t.circle(400,25)
                t.up()
                t.goto(110,-90)
                t.down()
                t.setheading(270)
                t.right(20)
                t.circle(400,13)
            elif t==f11:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.right(20)
                t.circle(400,15)
                t.up()
                t.goto(-110,-90)
                t.down()
                t.setheading(90)
                t.left(20)
                t.circle(-400,22.5)
                t.up()
                t.goto(-110,-90)
                t.down()
                t.setheading(270)
                t.left(20)
                t.circle(-400,13)
            elif t==f2:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.left(20)
                t.circle(-400,15)
                t.up()
                t.goto(140,-90)
                t.down()
                t.setheading(90)
                t.right(20)
                t.circle(400,22.5)
                t.up()
                t.goto(140,-90)
                t.down()
                t.setheading(270)
                t.right(20)
                t.circle(400,7)
                t.setheading(225)
                t.fd(150)
                
            elif t==f12:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.right(20)
                t.circle(400,15)
                t.up()
                t.goto(-140,-90)
                t.down()
                t.setheading(90)
                t.left(20)
                t.circle(-400,23.5)
                t.up()
                t.goto(-140,-90)
                t.down()
                t.setheading(270)
                t.left(20)
                t.circle(-400,7)
                t.setheading(315)
                t.fd(150)
            elif t==pt1:
                t.up()
                t.goto(0,105)
                t.down()
                t.fd(200);t.write("velocity=0 m/s\nPressure=1.68004 bar",move=True,font=("arial",10))
            elif t==pt2:
                t.up()
                t.goto(60,50)
                t.down()
                t.fd(200);t.write("velocity=9.821 m/s\nPressure=0.9247 bar",move=True,font=("arial",10))
            elif t==pt3:
                t.up()
                t.goto(0,-7)
                t.down()
                t.fd(200);t.write("velocity=0 m/s\nPressure=0.98479 bar",move=True,font=("arial",10))
            elif t==pt4:
                t.up()
                t.goto(-176.7,285)
                t.down()
                t.write("Pressure=1.0 bar",move=True,font=("arial",10))
    


#===================================heleshaw:ellipse=========================================    
def ellipse(*args):
    resetscreen()
    t=Turtle();t.hideturtle()
    t1=Turtle();t1.hideturtle()
    t2=Turtle();t2.hideturtle()
    t3=Turtle();t3.hideturtle()   
    setup(800,650)
    title("HELE SHAW")
    t2.speed("normal")
    t2.hideturtle()
    t2.up()
    t2.goto(-176.7,285)
    t2.write("SETTING UP THE APPARATUS",move=True,font=("arial",15))
    t.speed("normal")
    t.pensize(5)
    t1.speed("fastest")
    t.up()
    t1.up()
    t.goto(176.7,275)
    t1.goto(166.7,265)
    t.right(90)
    t1.right(90)
    t.down()
    t1.down()
    t.forward(400)
    t1.forward(380)
    t.right(45)
    t1.right(45)
    t.forward(250)
    t1.forward(235)
    t.right(90)
    t1.right(90)
    t.forward(250)
    t1.forward(235)
    t.right(45)
    t1.right(45)
    t.forward(400)
    t1.forward(380)
    t.right(90)
    t1.right(90)
    t.fd(353.5)
    t1.fd(332.34)
    t1.hideturtle()
    t.hideturtle()


    
    t3.up()                     #ellipse
    t3.goto(20,100)
    t3.down()
    t3.right(45)
    t3.fillcolor("gray")
    t3.begin_fill()
    for loop in range(2):        
            t3.circle(-50,90)    
            t3.circle(-50/2,90)
    t3.end_fill()
    t3.hideturtle()
    t2.clear()

    
    but1=Turtle();but1.speed("fastest");but1.hideturtle()
    but2=Turtle();but2.speed("fastest");but2.hideturtle()
    but1.up()
    but1.goto(120,-250)
    but1.down()
    for i in range(2):
            
            but1.fd(100)
            but1.right(90)
            but1.fd(30)
            but1.right(90)
    but1.up()
    but1.goto(125,-280)
    but1.down()
    but1.write("Proceed",font=("calibri",20,"normal"))

    but2.up()
    but2.goto(-120,-250)
    but2.down()
    for i in range(2):
            
            but2.fd(-100)
            but2.right(-90)
            but2.fd(-30)
            but2.right(-90)
    but2.up()
    but2.goto(-200,-280)
    but2.down()
    but2.write("circle",font=("calibri",20,"normal"))
    def proceed(x,y):
        print(x,y)
        if x>120 and x<220 and y<-250 and  y>-280:       
                but1.reset()
                elip()
        elif x<-120 and x>-220 and y<-250 and  y>-280:
                circle()           
    onscreenclick(proceed,1)
    listen()


    def elip():
        f1=Turtle();f1.speed("normal");f1.hideturtle()
        f2=Turtle();f2.speed("fastest");f2.hideturtle()
        f3=Turtle();f3.speed("fastest");f3.hideturtle()
        f4=Turtle();f4.speed("fastest");f4.hideturtle()
        f5=Turtle();f5.speed("fastest");f5.hideturtle()
        f6=Turtle();f6.speed("fastest");f6.hideturtle()
        f7=Turtle();f7.speed("fastest");f7.hideturtle()
        f8=Turtle();f8.speed("fastest");f8.hideturtle()
        f9=Turtle();f9.speed("fastest");f9.hideturtle()
        f10=Turtle();f10.speed("fastest");f10.hideturtle()
        f11=Turtle();f11.speed("fastest");f11.hideturtle()
        f12=Turtle();f12.speed("fastest");f12.hideturtle()
        f13=Turtle();f13.speed("fastest");f13.hideturtle()
        f14=Turtle();f14.speed("fastest");f14.hideturtle()
        f15=Turtle();f15.speed("fastest");f15.hideturtle()
        pt1=Turtle();pt1,speed("fastest");pt1.hideturtle()
        pt2=Turtle();pt2,speed("fastest");pt2.hideturtle()
        pt3=Turtle();pt3,speed("fastest");pt3.hideturtle()
        pt4=Turtle();pt4,speed("fastest");pt4.hideturtle()

        x=166
        for t in (f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13):
            t.up()
            t.color("pink")
        for t in f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13:
            t.goto(x,265)
            t.right(90)
            x-=27.5
        for t in (f1,f2,f3,f4,f5,f14,f6,f7,f8,f15,f9,f10,f11,f12,f13,pt1,pt2,pt3,pt4):
            t.down()
            if t==f1:
                t.fd(380)
                t.right(45)
                t.fd(232)
            elif t==f13:
                t.fd(380)
                t.left(45)
                t.fd(232)
            elif t==f6:
                t.pensize(6)
                t.fd(160)
                t.left(45)
                for loop in range(1):        
                    t.circle(-60,90)    
                    t.circle(-60/2,45)
                t.setheading(270)
                t.fd(270)
            elif t==f8:
                t.pensize(6)
                t.fd(160)
                t.right(45)
                for loop in range(1):        
                    t.circle(60,90)    
                    t.circle(60/2,45)
                t.setheading(270)
                t.fd(270)
            elif t==f14:
                t.up()
                t.color("pink")
                t.goto(46,268)
                t.pensize(6)
                t.setheading(270)
                t.down()
                t.fd(160)
                t.left(45)
                for loop in range(1):        
                    t.circle(-70,80)    
                    t.circle(-70/2,45)
                t.setheading(270)
                t.fd(230)
            elif t==f15:
                t.up()
                t.color("pink")
                t.goto(-46,268)
                t.pensize(6)
                t.setheading(270)
                t.down()
                t.fd(160)
                t.right(45)
                for loop in range(1):        
                    t.circle(70,80)    
                    t.circle(70/2,45)
                t.setheading(270)
                t.fd(230)
            elif t==f7:
                t.pensize(6)
                t.fd(155)
                t.setheading(180)
                t.circle(50,27.5)
                t.up()
                t.goto(0,110)
                t.setheading(0)
                t.down()
                t.circle(-50,27.5)
            elif t==f9:
                t.up()
                t.goto(-64,265)
                t.down()
                t.pensize(6)
                t.fd(140)
                t.right(45)
                t.circle(100,100)
                t.setheading(270)
                t.fd(180)
                t.left(40)
                t.fd(60)
            elif t==f5:
                t.up()
                t.goto(64,265)
                t.down()
                t.pensize(6)
                t.fd(140)
                t.left(45)
                t.circle(-100,100)
                t.setheading(270)
                t.fd(180)
                t.right(40)
                t.fd(60)
            elif t==f4:
                t.pensize(6)
                t.fd(130)
                t.left(45)
                t.circle(-125,90)
                t.right(10)
                t.fd(20)
                t.setheading(270)
                t.fd(145)
                t.right(45)
                t.fd(10)
            elif t==f10:
                t.pensize(6)
                t.fd(130)
                t.right(45)
                t.circle(125,90)
                t.right(10)
                t.fd(20)
                t.setheading(270)
                t.fd(138.5)
                t.left(45)
                t.fd(10)
            elif t==f3:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.left(20)
                t.circle(-400,15)
                t.up()
                t.goto(110,-90)
                t.down()
                t.setheading(90)
                t.right(20)
                t.circle(400,25)
                t.up()
                t.goto(110,-90)
                t.down()
                t.setheading(270)
                t.right(20)
                t.circle(400,12)
            elif t==f11:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.right(20)
                t.circle(400,15)
                t.up()
                t.goto(-110,-90)
                t.down()
                t.setheading(90)
                t.left(20)
                t.circle(-400,25)
                t.up()
                t.goto(-110,-90)
                t.down()
                t.setheading(270)
                t.left(20)
                t.circle(-400,12)
            elif t==f2:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.left(20)
                t.circle(-400,15)
                t.up()
                t.goto(140,-90)
                t.down()
                t.setheading(90)
                t.right(20)
                t.circle(400,25)
                t.up()
                t.goto(140,-90)
                t.down()
                t.setheading(270)
                t.right(20)
                t.circle(400,7)
                t.setheading(225)
                t.fd(150)
            elif t==f12:
                t.pensize(6)
                t.fd(100)
                t.setheading(270)
                t.right(20)
                t.circle(400,15)
                t.up()
                t.goto(-140,-90)
                t.down()
                t.setheading(90)
                t.left(20)
                t.circle(-400,25)
                t.up()
                t.goto(-140,-90)
                t.down()
                t.setheading(270)
                t.left(20)
                t.circle(-400,7)
                t.setheading(315)
                t.fd(150)
            elif t==pt1:
                t.up()
                t.goto(0,105)
                t.down()
                t.fd(200);t.write("velocity=0 m/s\nPressure=1.61004 bar",move=True,font=("arial",10))
            elif t==pt2:
                t.up()
                t.goto(45,70)
                t.down()
                t.fd(200);t.write("velocity=9.071 m/s\nPressure=0.98239 bar",move=True,font=("arial",10))
            elif t==pt3:
                t.up()
                t.goto(2,20)
                t.down()
                t.fd(200);t.write("velocity=0 m/s\nPressure=0.99479 bar",move=True,font=("arial",10))
            elif t==pt4:
                t.up()
                t.goto(-176.7,285)
                t.down()
                t.write("Pressure=1.0 bar",move=True,font=("arial",10))
    
        

        



b1=Button(s1,text="circle",command=circle)
b1.pack(side=BOTTOM,pady=10)
b2=Button(s1,text="ellipse",command=ellipse)
b2.pack(side=BOTTOM)
win.mainloop()
